# Generated by Django 3.2.5 on 2021-10-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_from',
            field=models.CharField(default='uu', max_length=20),
            preserve_default=False,
        ),
    ]
